name: Workflow deploiement Ansible
on:
  push:
    branches:
    - master
    path:
    - Ansible/*

jobs:

  build-and-deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.1.1
      with:
    # Ansible playbook filepath
        playbook: ./Ansible/main.yml
    # Root directory of Ansible project (defaults to current)
        directory: ./
    # SSH private key used to connect to the host
        key: ${{secrets.SSH_PRIVATE_KEY}}
    # Custom content to write into hosts
        inventory: |
          [all]
          workshopdevopspierrc.eastus2.cloudapp.azure.com



        


