name: Workflow deploiement d'une VM dans un "resource group"
on:
  push:
    branches:
    - master
    path:
    - ARM/*

jobs:
  build-and-deploy:
    name: Deploiement dans Azure
    runs-on: ubuntu-latest    
    steps:
    - name: Azure Login Az Cli
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}