name: Workflow deploiement du Site Web
on:
  push:
    branches:
    - master
    path:
    - Web/*
    - Ansible/*


jobs:
  build-and-deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
        [all]
        20.49.40.32

