name: Workflow deploiement du site web
on:
  push:
    branches:
    - master
    path:
    - Web/*

jobs:
  build-and-deploy:
    name: Deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master      