name: Workflow deploiement du site web
on:
  push:
    branches:
    - master
    path:
    - './Web/*'

jobs:
  build-and-deploy:
    name: Deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Setup remote
      run:  |
        echo "${{secrets.SSH_PUBLIC_KEY}}" | sudo tee /etc/ssh/authorized_keys
        sudo tee /etc/ssh/sshd_config <<EOF
          PasswordAuthentication no
          PubkeyAuthentication yes
          AuthorizedKeysFile /etc/ssh/authorized_keys
          PermitRootLogin no
          Subsystem sftp /usr/lib/openssh/sftp-server
        EOF
        sudo systemctl restart sshd

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: ./Ansible
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [all]
          20.36.191.190