name: Workflow deploiement du site web
on:
  push:
    branches:
    - master
    path:
    - './Web/*'

jobs:
  build-and-deploy:
    name: Deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Run playbook
      uses: jawher/action-ansible@2.9.7
      env:
        ANSIBLE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: ansible-playbook -i Ansible/hosts.yml Ansible/main.yml
