name: Workflow deploiement d'un Site Web dans la VM"
on:
  push:
    branches:
    - master
    path:
    - Web/*

jobs:
  build-and-deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: web.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [all]
          workshopdevopspierrc.eastus2.cloudapp.azure.com

